spring.application.name=sentinel-security

spring.datasource.url=jdbc:postgresql://localhost:5432/sentinelCore-secureOps
spring.datasource.username=postgres
spring.datasource.password=ram123

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


sentinelcore.ai.opencode.api-key=sk-3TAqjcsBasBg2L7jk5GFoVHCVncSZG8SYy8gCtWMlMGMyk4cwvuEREYMK5ukbRvM
sentinelcore.ai.opencode.model=deepseek-v4-flash-free
sentinelcore.ai.opencode.endpoint=https://opencode.ai/zen/v1/chat/completions

#logging.level.org.springframework.security=DEBUG